### ISSUE TITLE
CNAME tracker smartproxy.dataunlocker.com

### ISSUE THREAD

**Issue by douira** [AdguardTeam/cname-trackers#15]
The domain `smartproxy.dataunlocker.com` is cloaked with CNAME and is a tracking proxy. See [this entry](https://github.com/uBlockOrigin/uAssets/commit/b9ec22af5c9e2c7fe9ebbcd0aa49fde50094dcaf) in uBlock Origin's assets for reference. Here's an example website: https://woodbrass.com/. It uses the domain 1bw7etm93lf.www.woodbrass.com to cloak tracking requests. The subdomain is random and might change, but doesn't do so very often. (Dataunlocker's website mentions this). It would be nice if it was added as a host for blocking though DNS.

**Comment by slavaleleka** [comment]
thanks for your report!

I see that `smartproxy.dataunlocker.com` is cname for `1bw7etm93lf.www.woodbrass.com` but there are some issues with our `urlfilter` and [no cloaked trackers found](https://uploads.adguard.com/slbdzdrvj5xg8.png)

**Comment by douira** [comment]
So is this a matter of classifying dataunlocker as a tracker then?

**Comment by ameshkov** [comment]
Nope, probably a bug

**Comment by ameshkov** [comment]
@slavaleleka `dataunlocker.com` should be added to the list of trackers first before doing the check.

**Comment by slavaleleka** [comment]
done!

so dataunlocker disguised trackers will be in AdGuard Tracking Protection filter soon

**Comment by JobcenterTycoon** [comment]
They change the domain every couple of weeks.

`welcoming-carpets.tk`
`creative-banana.tk` (actual in use)

With the CNAME tool i found many unblocked tracking domains please take a look

**Comment by slavaleleka** [comment]
done

**Comment by JobcenterTycoon** [comment]
@slavaleleka there are still missing domains like:
```
umhadn49kldc.www.jeddd.com
s5kxumf4kxzn.www.botcomics.com
ooyk93cxdqv8.www.usa-corporate.com
qt5jl7r111h7.allesvoormijnvakantie.nl
1796kpkzuwj.www.hawpar.com
```

resolving to `delightful-development.ml`

**Comment by slavaleleka** [comment]
those domains should be "detected" by AdGuard DNS for further collecting. so if they were not resolved with AdGuard DNS recently, we can do nothing to force their gathering as disguised trackers

**Comment by spirillen** [comment]
> those domains should be "detected" by AdGuard DNS for further collecting. so if they were not resolved with AdGuard DNS recently, we can do nothing to force their gathering as disguised trackers

Yes they "should"(n't) as they are running with A records...

There are not to my knowledge any way we can pick this up on a DNS level. If this should be made any way possible, I think we (you) would need to ensure this on a IP level, the problem is, what else is running on these IP addresses?

```
drill anti-adblock.herokuapp.com @9.9.9.10
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 17671
;; flags: qr rd ra ; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 0 
;; QUESTION SECTION:
;; anti-adblock.herokuapp.com.  IN      A

;; ANSWER SECTION:
anti-adblock.herokuapp.com.     6       IN      A       54.78.134.111
anti-adblock.herokuapp.com.     6       IN      A       34.241.115.67
anti-adblock.herokuapp.com.     6       IN      A       54.228.42.199
```

**Comment by ameshkov** [comment]
@spirillen what we mean here is that the domains indeed may have those CNAMEs, but if we haven't noticed a single A/AAAA query to those domains on AdGuard DNS, they're simply not used in the wild, therefore there's no need to keep them in the list.

**Comment by JobcenterTycoon** [comment]
@slavaleleka a few sites now hide the sub domain behind a reverse proxy like Cloudflare. Example is `https://monumentmetals.com/` -> `seqrukcdgs7m.monumentmetals.com` -> A cloudflare IP.

![photo_2022-01-24_19-21-08](https://user-images.githubusercontent.com/48647394/154513892-27772221-ec44-4d5c-8613-25ed014c185b.jpg)

It is possible to cover this too?

**Comment by ameshkov** [comment]
This would be MUCH harder to detect and analyzing just the DNS is not enough here.

**Comment by JobcenterTycoon** [comment]
Im here because of https://github.com/AdguardTeam/AdguardFilters/issues/113442#issuecomment-1076330035

So not fixable at the moment?

**Comment by JobcenterTycoon** [comment]
> Not yet, but we plan to find a way to discover trackers hidden by reverse proxies a well.

Any progress on this? Multiply sites using Cloudflare. Examples:

```
eldorado.gg
trybawaryjny.pl
bolighub.dk
adria.gg
```

**Comment by ameshkov** [comment]
What domain belongs to Dataunblocker there?

**Comment by JobcenterTycoon** [comment]
```
w9g7dlhw3kaank.www.eldorado.gg
yctjw54slxrwwlh.trybawaryjny.pl
nrpukcsgboqr0gz2o8.www.bolighub.dk
ce1pe4ndesg6.adria.gg
```

All point to Cloudflare IP adresses and are uncatched.
